name: widget-server pipe DockerHUB

on:
  push:
    branches:
      - main-dockerhub
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        id: login-docker-hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Use the DockerHub token as password
          # This is a personal access token with the `write:packages` scope
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "SHA=$SHA" >> $GITHUB_OUTPUT

      - name: Build and push image DcokerHub
        id: build-push-image
        env:
          DOCKER_HUB_REGISTRY: ${{ vars.DOCKER_HUB_REGISTRY }}
          IMAGE_TAG: ${{ steps.generate_tag.outputs.SHA }}
        run: | 
          docker build -t $DOCKER_HUB_REGISTRY:$IMAGE_TAG .
          docker push $DOCKER_HUB_REGISTRY:$IMAGE_TAG

